src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use App\Validator\GameHasDifferentPlayers;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[GameHasDifferentPlayers]
#[ORM\Entity(repositoryClass: GameRepository::class)]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(mappedBy: '_game', cascade: ['persist', 'remove'])]
    private ?GameResult $gameResult = null;

    #[ORM\ManyToOne(inversedBy: 'games')]
    private ?Scenario $_scenario = null;

    /**
     * @var Collection<int, PlayerGame>
     */
    #[ORM\OneToMany(targetEntity: PlayerGame::class, mappedBy: '_game', cascade: ['persist'])]
    private Collection $playerGames;

    private ?PlayerGame $player1 = null;
    private ?PlayerGame $player2 = null;

    public function __construct()
    {
        $this->playerGames = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGameResult(): ?GameResult
    {
        return $this->gameResult;
    }

    public function setGameResult(GameResult $gameResult): static
    {
        // set the owning side of the relation if necessary
        if ($gameResult->getGame() !== $this) {
            $gameResult->setGame($this);
        }

        $this->gameResult = $gameResult;

        return $this;
    }

    public function getScenario(): ?Scenario
    {
        return $this->_scenario;
    }

    public function setScenario(?Scenario $_scenario): static
    {
        $this->_scenario = $_scenario;

        return $this;
    }

    /**
     * @return Collection<int, PlayerGame>
     */
    public function getPlayerGames(): Collection
    {
        return $this->playerGames;
    }

    public function addPlayerGame(PlayerGame $playerGame): static
    {
        if (!$this->playerGames->contains($playerGame)) {
            $this->playerGames->add($playerGame);
            $playerGame->setGame($this);
        }

        return $this;
    }

    public function removePlayerGame(PlayerGame $playerGame): static
    {
        if ($this->playerGames->removeElement($playerGame)) {
            // set the owning side to null (unless already changed)
            if ($playerGame->getGame() === $this) {
                $playerGame->setGame(null);
            }
        }

        return $this;
    }

    /**
     * Get the value of player1
     */ 
    public function getPlayer1()
    {
        return $this->player1;
    }

    /**
     * Set the value of player1
     *
     * @return  self
     */ 
    public function setPlayer1($player1)
    {
        $this->player1 = $player1;

        return $this;
    }

    /**
     * Get the value of player2
     */ 
    public function getPlayer2()
    {
        return $this->player2;
    }

    /**
     * Set the value of player2
     *
     * @return  self
     */ 
    public function setPlayer2($player2)
    {
        $this->player2 = $player2;

        return $this;
    }
}

src/Entity/PlayerGame.php
<?php

namespace App\Entity;

use App\Repository\PlayerGameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayerGameRepository::class)]
class PlayerGame
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'playerGames')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $_player = null;

    #[ORM\ManyToOne(inversedBy: 'playerGames')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Game $_game = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Faction $_faction = null;

    /**
     * @var Collection<int, PlayerGameResult>
     */
    #[ORM\OneToMany(targetEntity: PlayerGameResult::class, mappedBy: '_player_game')]
    private Collection $playerGameResults;

    public function __construct()
    {
        $this->playerGameResults = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlayer(): ?User
    {
        return $this->_player;
    }

    public function setPlayer(?User $_player): static
    {
        $this->_player = $_player;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->_game;
    }

    public function setGame(?Game $_game): static
    {
        $this->_game = $_game;

        return $this;
    }

    public function getFaction(): ?Faction
    {
        return $this->_faction;
    }

    public function setFaction(?Faction $_faction): static
    {
        $this->_faction = $_faction;

        return $this;
    }

    /**
     * @return Collection<int, PlayerGameResult>
     */
    public function getPlayerGameResults(): Collection
    {
        return $this->playerGameResults;
    }

    public function addPlayerGameResult(PlayerGameResult $playerGameResult): static
    {
        if (!$this->playerGameResults->contains($playerGameResult)) {
            $this->playerGameResults->add($playerGameResult);
            $playerGameResult->setPlayerGame($this);
        }

        return $this;
    }

    public function removePlayerGameResult(PlayerGameResult $playerGameResult): static
    {
        if ($this->playerGameResults->removeElement($playerGameResult)) {
            // set the owning side to null (unless already changed)
            if ($playerGameResult->getPlayerGame() === $this) {
                $playerGameResult->setPlayerGame(null);
            }
        }

        return $this;
    }
}

src/Entity/PlayerGameResult.php
<?php

namespace App\Entity;

use App\Repository\PlayerGameResultRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayerGameResultRepository::class)]
class PlayerGameResult
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'playerGameResults')]
    #[ORM\JoinColumn(nullable: false)]
    private ?GameResult $_game_result = null;

    #[ORM\ManyToOne(inversedBy: 'playerGameResults')]
    #[ORM\JoinColumn(nullable: false)]
    private ?PlayerGame $_player_game = null;

    #[ORM\Column]
    private ?int $tournament_points = null;

    #[ORM\Column]
    private ?int $objective_points = null;

    #[ORM\Column]
    private ?int $survivor_points = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGameResult(): ?GameResult
    {
        return $this->_game_result;
    }

    public function setGameResult(?GameResult $_game_result): static
    {
        $this->_game_result = $_game_result;

        return $this;
    }

    public function getPlayerGame(): ?PlayerGame
    {
        return $this->_player_game;
    }

    public function setPlayerGame(?PlayerGame $player_game): static
    {
        $this->_player_game = $player_game;

        return $this;
    }

    public function getTournamentPoints(): ?int
    {
        return $this->tournament_points;
    }

    public function setTournamentPoints(int $tournament_points): static
    {
        $this->tournament_points = $tournament_points;

        return $this;
    }

    public function getObjectivePoints(): ?int
    {
        return $this->objective_points;
    }

    public function setObjectivePoints(int $objective_points): static
    {
        $this->objective_points = $objective_points;

        return $this;
    }

    public function getSurvivorPoints(): ?int
    {
        return $this->survivor_points;
    }

    public function setSurvivorPoints(int $survivor_points): static
    {
        $this->survivor_points = $survivor_points;

        return $this;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use App\Entity\GameResult;
use App\Entity\Scenario;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('_scenario', EntityType::class, [
                'class' => Scenario::class,
                'label' => 'Scénario joué',
            ])
            ->add('player1', PlayerGameType::class)
            ->add('player2', PlayerGameType::class)
            ->add('gameResult', GameResultType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Entity\GameResult;
use App\Entity\PlayerGame;
use App\Entity\PlayerGameResult;
use App\Form\GameResultType;
use App\Form\GameType;
use App\Repository\GameRepository;
use App\Repository\GameResultRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class GameController extends AbstractController
{
    #[Route('/games', name: 'game_list')]
    public function index(GameRepository $repository): Response
    {
        $games = $repository->findAllWithResultOrderedByDate();

        return $this->render('game/index.html.twig', [
            'games' => $games,
        ]);
    }

    #[Route('/games/new-game-withresult', name: 'game__with_result_new')]
    public function newResult(Request $request, EntityManagerInterface $entityManager): Response
    {
        $game = new Game();

        $form = $this->createForm(GameType::class, $game);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $game->getGameResult()->setDate(new \DateTime());
            $game->getGameResult()->setRegisteredBy($this->getUser());
            $game->getGameResult()->setStatus(GameResult::STATUS_WAITING_VALIDATION);

            // Calculate tournament points for both players:
            $player1OP = $game->getGameResult()->getPlayer1Result()->getObjectivePoints();
            $player2OP = $game->getGameResult()->getPlayer2Result()->getObjectivePoints();
            if($player1OP == $player2OP){
                $player1TP = $player2TP = 2;
            }
            else if($player1OP > $player2OP){
                $player1TP = 4;
                $player2TP = (($player1OP - $player2OP) <= 2) ? 1 : 0;
            }
            else{
                $player2TP = 4;
                $player1TP = (($player2OP - $player1OP) <= 2) ? 1 : 0;
            }
            if($player1OP >= 5) $player1TP++;
            if($player2OP >= 5) $player2TP++;

            $game->getGameResult()->getPlayer1Result()->setTournamentPoints($player1TP);
            $game->getGameResult()->getPlayer2Result()->setTournamentPoints($player2TP);

            $game->getGameResult()->getPlayer1Result()->setPlayerGame($game->getPlayer1());
            $game->getGameResult()->getPlayer2Result()->setPlayerGame($game->getPlayer2());
            
            $game->addPlayerGame($game->getPlayer1());
            $game->addPlayerGame($game->getPlayer2());
            $game->getGameResult()->addPlayerGameResult($game->getGameResult()->getPlayer1Result());
            $game->getGameResult()->addPlayerGameResult($game->getGameResult()->getPlayer2Result());

            $entityManager->persist($game);
            $entityManager->flush();
    
            return $this->redirectToRoute('game_list');
        }
    
        return $this->render('game/new_game_with_result.html.twig', [
            'form' => $form,
        ]);
    }
    

}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Latest Games{% endblock %}

{% block body %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="mb-0">Dernières parties</h1>
        <a href="{{ path('game__with_result_new') }}" class="btn btn-success">
            <i class="bi bi-plus"></i> Enregistrer un résultat
        </a>
    </div>

    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>Date</th>
                <th colspan=3>Joueur 1</th>
                <th colspan=3>Joueur 2</th>
                <th>Scénario</th>
            </tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr>
                <td>{{ game.gameResult.date ? game.gameResult.date|date('Y-m-d') : 'N/A' }}</td>
                {% for playerResult in game.gameResult.playerGameResults %}
                    {% if loop.index == 1 %}
                        <td>
                            {% if playerResult.playerGame.player.avatar %}
                                <img src="https://cdn.discordapp.com/avatars/{{ playerResult.playerGame.player.discordId }}/{{ playerResult.playerGame.player.avatar }}.png" alt="Avatar" class="rounded-circle" width="30" height="30">
                            {% endif %}
                            {{ playerResult.playerGame.player }}
                        </td>
                        <td>
                            <img width="30" height="30" class="rounded-circle me-2" src="{{ playerResult.playerGame.faction.logo }}" alt="Logo pour {{ playerResult.playerGame.faction.label }}" title="{{ playerResult.playerGame.faction.label }}"/>
                        </td>
                        <td>
                            {{ playerResult.objectivePoints }} ({{ playerResult.survivorPoints }})
                        </td>
                    {% endif %}
                    {% if loop.index == 2 %}
                        <td>
                            {{ playerResult.objectivePoints }} ({{ playerResult.survivorPoints }})
                        </td>
                        <td>
                            <img width="30" height="30" class="rounded-circle me-2" src="{{ playerResult.playerGame.faction.logo }}" alt="Logo pour {{ playerResult.playerGame.faction.label }}" title="{{ playerResult.playerGame.faction.label }}"/>
                        </td>
                        <td>
                            {% if playerResult.playerGame.player.avatar %}
                                <img src="https://cdn.discordapp.com/avatars/{{ playerResult.playerGame.player.discordId }}/{{ playerResult.playerGame.player.avatar }}.png" alt="Avatar" class="rounded-circle" width="30" height="30">
                            {% endif %}
                            {{ playerResult.playerGame.player }}
                        </td>
                    {% endif %}
                {% endfor %}
                <td>{{ game.scenario }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5" class="text-center">No games yet.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/game/new_game_with_result.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Game{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1>Nouveau résultat de partie</h1>

    {{ form_start(form) }}
        {# {{ form_widget(form) }} #}
        <div class="row mb-3">
            {{ form_label(form._scenario) }}
            {{ form_widget(form._scenario) }}
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <h5>Joueur 1</h5>
                <div class="row">
                    <div class="col-md-6">
                        {{ form_label(form.player1._player) }}
                        {{ form_widget(form.player1._player) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_label(form.player1._faction) }}
                        {{ form_widget(form.player1._faction) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form_label(form.gameResult.player1Result.objectivePoints) }}
                        {{ form_widget(form.gameResult.player1Result.objectivePoints) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_label(form.gameResult.player1Result.survivorPoints) }}
                        {{ form_widget(form.gameResult.player1Result.survivorPoints) }}
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <h5>Joueur 2</h5>
                <div class="row">
                    <div class="col-md-6">
                        {{ form_label(form.player2._player) }}
                        {{ form_widget(form.player2._player) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_label(form.player2._faction) }}
                        {{ form_widget(form.player2._faction) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        {{ form_label(form.gameResult.player2Result.objectivePoints) }}
                        {{ form_widget(form.gameResult.player2Result.objectivePoints) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_label(form.gameResult.player2Result.survivorPoints) }}
                        {{ form_widget(form.gameResult.player2Result.survivorPoints) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-center gap-3 mt-4">
            {{ form_row(form._token) }}
            <button type="submit" class="btn btn-success">Sauvegarder</button>
            <a href="{{ path('game_list') }}" class="btn btn-secondary">Retour</a>
        </div>
    {{ form_end(form, { render_rest: false }) }}
</div>
{% endblock %}